services:
  fms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fms-app
    ports:
      - "5001:5000"
    environment:
      FLASK_DEBUG: "1"
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./app.py:/app/app.py
      - ./static:/app/static
      - ./templates:/app/templates
      - ./requirements.txt:/app/requirements.txt
      - ./uploads:/app/uploads
      - ./fms.db:/app/fms.db
    working_dir: /app
    command: python app.py
